Presentation branch fragments
RafaX8/movies-and-shows-api pull request #8
Opened 2022-11-22 16:32 UTC by RafaX8

## Description de la tarea

Implementados los fragmentos para la interfaz gráfica de usuario junto a safe navigation.
Terminado el layout para MovieDetails

## ¿Cómo se ha implementado?

Creado una estructura de carpetas y archivos de la capa presentation que se interrelacionan mediante herencia y paso de parámetros, y se enlazan con los layouts gracias a Binding. Por otro lado, se ha implementado la navegación segura entre fragmentos.
Se han implementado también una serie de recursos interesantes a la hora de maquetar los layouts, como CardView y NestedScrollView.

**#ORDEN DE DESARROLLO DE LAS CLASES:**

1. Movie[Feed/Detail]ViewModel: 
Clase que recibe el Caso de Uso del fragmento en particular al que se referencia y hereda de ViewModel. Esta clase permite cargar los datos del caso de uso y transmitirlos al hilo principal mediante LiveData y Coroutines.

2. Movie[Feed/Detail]Fragment: 
Clase que hereda de Fragment, similar a las Activities, pero permite la visualización de layouts de manera que podemos superponer un Fragment sobre otro como una pila (LIFO, Last In First Out) y movernos de uno a otro sin tener que cargar y destruir Activities.
Esta clase se enlaza con su layout correspondiente mediante binding, y de esta manera se permite visualizar los datos del ViewModel que recibe de la clase MovieFactory, donde se recogen una serie de funciones para la ejecución de casos de uso.
En la clase de MovieFeedFragment se añade una función que se ejecuta al hacer click en la el item correspondiente para navegar entre Fragmentos (de Feed a Detail).

3. MovieFeedViewHolder:
Clase que hereda de RecyclerView.ViewHolder y recibe una vista como parámetro que se utiliza para enlazar los datos del caso de uso con los datos que vamos a ver en el RecyclerView así como establecer acciones con las vistas (view_items) que se muestran en pantalla. En este caso, por ejemplo, cada vista tiene una acción de click que abre las vistas de Details.

4. MovieAdapter: 
Clase concretamente necesaria para la visualización de RecyclerViews. Esta clase solo es necesaria en MovieFeedFragment y hereda de un ViewHolder.

5. nav_graph
Fichero de recursos que recoge los fragmentos de la aplicación y establece un grafo de movimientos entre fragmentos. En este caso, solo es una acción que mueve de Feed a Detail.

6. Capa de layouts.
En resumidas cuentas: activity_main tiene un FragmentContainer que permite la visualización de los fragmentos que hemos creado. Primeramente ejecuta fragment_movie_feed, que incluye un RecyclerView con los items correspondientes. Luego cada item está relacionado con el fragment_movie_detail, que a su vez incluye el layout de cada película con sus datos.

## Keywords

Fragments, Views, ViewHolder, Factory, Items, Themes, Material3, Safe Navigation.

## Screenshots or Video

**Vídeo Resumen de la app**
https://user-images.githubusercontent.com/104196849/203405551-489d29bd-6f47-400e-8708-f8b24771239e.mp4

**Capturas**
- Light Mode
![image](https://user-images.githubusercontent.com/104196849/203405886-40445d0f-d370-4caa-b7ee-cb7b0b674828.png)
![image](https://user-images.githubusercontent.com/104196849/203406098-cce7198d-8ca0-4dd9-8ef6-cf9bdc8749bf.png)

- Dark Mode
![image](https://user-images.githubusercontent.com/104196849/203570818-74bbd901-1adb-4db8-a9af-e807c07479f3.png)
![image](https://user-images.githubusercontent.com/104196849/203571108-fa76abd5-93ad-432b-aaf5-a3fb9ff2e454.png)

## Objetivos

## Criterios de Evaluación

2022-11-23 15:05 UTC, albertoag128 commented on app/src/main/AndroidManifest.xml
> +        <!-- TEST -> BORRAR DESPUES -->
Buenas Rafaa, se te ha olvidado borrar esto

2022-11-23 15:07 UTC, albertoag128 commented on app/src/main/java/com/rafaelmardom/movies_and_shows_api/presentation/MovieDetailFragment.kt
> +        viewModel?.loadMovieDetails(arguments?.getString("movieId") ?: "0") // ESTO ES LO QUE DA ERROR
Los comentarios Rafa porfa, que esto lo podría ver otra gente y si ya funciona todo como indican las capturas, podría incitar a error

2022-11-23 15:08 UTC, albertoag128 commented on app/src/main/java/com/rafaelmardom/movies_and_shows_api/presentation/MovieFactory.kt
> +    /*
Los comentarios porfa

2022-11-23 15:09 UTC, albertoag128 commented on app/src/main/java/com/rafaelmardom/movies_and_shows_api/presentation/MovieFeedFragment.kt
> +        Log.d("@dev", "navigate")
Rafa ten cuidado con los Log, si has terminado de depurar o simplemente ver si la ejecucion del codigo entra por ahi, eliminalos porfa

2022-11-23 15:10 UTC, albertoag128 commented on app/src/main/java/com/rafaelmardom/movies_and_shows_api/presentation/adapter/MovieDetailViewHolder.kt
> +        // ANTES DE HACER ESTO: CREAR UNA CLASE PARA USAR EL REPOSITORIO GLIDE.
los comentarios

2022-11-23 15:12 UTC, albertoag128 commented on app/src/main/java/com/rafaelmardom/movies_and_shows_api/presentation/adapter/MovieFeedViewHolder.kt
> +        binding.movieRating.text = movie.rating.toString() // Este es double
Los comentarios de nuevo. Ademas de eso me gustaria mencionar como sugerencia que en principio si no vamos a operar con numeros, aunque en la api vengan en formato int o double, los podemos recoger como string

2022-11-23 15:14 UTC, albertoag128 commented on app/src/main/res/layout/view_item_movie_detail.xml
> +            android:id="@+id/movie_title"
Si te gusta más trabajar con linear layout esta genial Rafa, aunque Android nos recomienda no tener más de 3/4 hijos debido a lo complejas que se pueden volver las vistas, mientras que lo controles todo perfecto tío. Pd: muy buena estructura de componentes

2022-11-23 15:16 UTC, albertoag128 commented on app/src/main/res/navigation/nav_graph.xml
> +            app:nullable="false">
Dado que has declarado que el argumento no puede ser nulo, quizas te interesaría añadir un valor por defecto que por ejemplo fuera ""

2022-11-23 15:18 UTC, albertoag128 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="movie_img_size_xxl">512dp</dimen>
Me gusto mucho esto que has implementado aunque no se si esos tamaños están bien, a ver si @josem-perram nos puede comentar algo al respecto para aprender acerca de esto

2022-11-23 15:19 UTC, albertoag128 commented on app/src/main/res/values/strings.xml
> +    <string name="sample_year">2002</string>
Estos samples los utilizas luego en la app? O sólo eran pruebas para el diseño?

2022-11-23 15:24 UTC, albertoag128 approved these changes
En lineas generales es un muy buen trabajo Rafael, lo único que tenemos que tener más cuidado cuando dejamos codigo comentado o logs por ahí (te entiendo al 100% porque a mi tambien me pasa xD). Aun así enhorabuena tío, es muy buen trabajo, sigue así que el esfuerzo será recompensado. 
🚀🚀

2022-11-23 15:24 UTC, RafaX8 commented on app/src/main/res/values/strings.xml
> +    <string name="sample_year">2002</string>
Los utilizo como texto de prueba para ver donde se posicionan los elementos y hacer una vista previa del diseño :)

2022-11-23 15:25 UTC, RafaX8 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="movie_img_size_xxl">512dp</dimen>
Gracias capo. Es verdad que muchos acaban sobrando, así que podría quitar los que sé que no utilizo, la verdad.

2022-11-23 15:25 UTC, RafaX8 commented on app/src/main/res/navigation/nav_graph.xml
> +            app:nullable="false">
Lo tendré en cuenta :)

2022-11-23 15:31 UTC, RafaX8 commented on app/src/main/res/layout/view_item_movie_detail.xml
> +            android:id="@+id/movie_title"
He intentado trabajar con un poco de todo y es cierto que algún componente a acabado recibiendo ayudas por familia numerosa 😂

2022-11-23 15:33 UTC, RafaX8 commented
Muchas gracias por tu feedback👌 Repasaré todo el código y comentarios innecesarios y los borraré para dejar el código limpio.

2022-11-30 15:36 UTC, jmperezra requested changes
Please, revisa los comentarios. La vista xml hay que mejorarla, se han creado muchos hijos innecesarios. Cuidado con el concepto styles vs dimens.

2022-11-30 15:36 UTC, jmperezra commented on app/src/main/java/com/rafaelmardom/movies_and_shows_api/presentation/MovieFeedViewModel.kt
> +        val moviesFeed: List<GetMoviesFeedUseCase.MovieFeed> = emptyList()
Deberías meter un loading para informar al usuario de que se están cargando datos

2022-11-30 15:36 UTC, jmperezra commented on app/src/main/res/layout/fragment_movie_detail.xml
> +    <include
El include lo usamos cuando vamos a reutilizar vistas, en este caso, no necesitamos hacerlo porque la vista de detalle no se reutiliza.

2022-11-30 15:36 UTC, jmperezra commented on app/src/main/res/layout/view_item_movie_detail.xml
> +            android:id="@+id/movie_title"
Rafa, esta vista se puede hacer con la mitad de componentes usados. Con un scroll + un constraints y los textview para visualizar los datos es suficiente. Please, refactoriza e intenta usar lo indicado.

2022-11-30 15:36 UTC, jmperezra commented on app/src/main/res/layout/view_item_movie_detail.xml
> +            <androidx.cardview.widget.CardView
Mejor dejar los CardView para cuando se usen los RecyclerViews.

2022-11-30 15:36 UTC, jmperezra commented on app/src/main/res/navigation/nav_graph.xml
> +            app:nullable="false">
Al meter el nullable a false, significa que si le pasan un valor nulo, la aplicación va a hacer crash. Quizás esto debería ser así pues no deben llegar valores nulos. Si queremos mostrar un error cuando llegue un valor nulo, entonces habría que indicar un valor por defecto y tratar ese valor para mostrar un mensaje de error al usuario.

2022-11-30 15:36 UTC, jmperezra commented on app/src/main/res/values/dimens.xml
> +    <dimen name="movie_img_size_xxl">512dp</dimen>
Eso es, declaramos sólo valores que se van a usar. 512dp quizás me parece demasiado. Además, en dimens debemos diferenciar que son estilos (title, subtitle) y que son valores de dimens (text_size, movie_img)... Estas mezclando ambos concepto en el fichero dimens. Los primeros van en style los segundos si van en dimens.

2022-12-01 11:40 UTC, RafaX8 commented
¡Buenos días!
Ya he realizado todas las correcciones que me habéis indicado, y creo que está todo en orden:
- He reestructurado el detail layout para que no dependa de tantos padres e hijos.
> No me gusta como ha quedado el diseño de este layout, ahora que tiene los bordes puntiagudos, pero de momento me interesa más saber si la estructura del fichero está correctamente. Si el diseño es regulero, estoy dispuesto a mejorarlo más adelante.
- He eliminado comentarios, código innecesario y dimens que no procedian en dicho archivo y/o no se utilizaban.
> Para mí sorpresa, algunos sí se utilizaban como el de la imagen xxl. También he aprovechado para renombrar algunos de ellos.
- He implementado Skeleton (aunque no se aprecia a la hora de ejecutar la App, la verdad, esto lo hablaré con @josem-perram en clase)

Espero vuestra segunda opinión :)

2022-12-18 19:41 UTC, merged